[package]
name = "extra_practice"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "expression_evaluation"
path = "src/expression_evaluation.rs"




# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
